### PR TITLE
Refactor utreexo/cmd/

### PR DESCRIPTION
**Pull request by kcalvinalvin**
Everything in ```utreexo/cmd/``` is refactored.

While reviewing code to do the TODOs mentioned in #79, I noticed some things to clean up.

### This refactor is needed for the goals mentioned in #79 as it separates

1. Bridge node and CSN (Compact State Node)
2. Chain resume functionality from both bridgenode and csn (placed in ```chain.go``` and ```chainio.go``` in both ```bridgenode/``` and ```csn/```

#### Changed things

1. All functionality for store and restore to disk is now placed in ```chain.go``` and ```chainio.go``` in both ```bridgenode/``` and ```csn/```

2. Various bugs involving offsetfile.go was fixed. To add new blocks from ```blk*.dat``` files, all the user has to do is delete the ```offsetdata``` directory and re-run ```genproofs``` to rebuild the offset index. Both ```genproofs``` and ```ibdsim``` will resume where they left off and sync the new blocks.

3. ```main.go``` file in directory ```cmd/``` is the main file now. Also
removed some unused variables.

4. Separated all ttl related things to its own directory.

5. Updated ```readme.md``` in ```utreexo/cmd/``` and in ```utreexo/```

6. Removed all names related or implying a simulator.

7. Various comment cleanups in all files

### CODE REVIEW

**Comment by somsakpanom** [comment]
รับBitcoเหริญ สนับสนุนเพื่อที่จะสามารถเอาไปแปลงแลกเปลี่ยนเป็นเงินสดใช้จ่ายได้

**Comment by adiabat** [comment]
This is great -- I like how it's organized a lot better.  There are a couple little things I want to fix / change, but I think it's better to merge it and tweak stuff later so we can base stuff off of this code reorg.

**Comment by adiabat** [comment]
post-merge comments:

we should call this something other than "cmd" :)

it could be ... utreexo, and then the library is libutreexo?  Or utreexo stays the library, and the node binaries are something else?  There's a lot of logic and things going on that's outside of the library at this point, so it needs it's own name; it's still "simulating" IBD, but we're getting past the point of being a simulation; once tx validation is in, it's basically IBD.

Simutils -> util, but we should call that something else as well.  It's utils for the cmd.

utreexo -> libutreexo, cmd -> utreexo, util -> utilutreexo? utrils? 
or cmd can be "unode" or "csn" or something.

Anyway it's basically just naming things which is one of the 2 or 3 hard problems in CS :)

**Comment by kcalvinalvin** [comment]
I... must admit I'm terrible at naming things. If you feel like something is better, do change them!

**Pull request merged**
