### PR TITLE
.github/: Add an integration test step

### PR DESCRIPTION
**Pull request by dergoegge**

### CODE REVIEW

**Comment by dergoegge** [comment]
It's kind of stupid that the download of bitcoind adds ~2min.

**Comment by kcalvinalvin** [comment]
lines 685 and 686 on integration test logs
```
User exit signal received. Exiting...
##[error]blockServer accept error: accept tcp 127.0.0.1:8338: use of closed network connection
```

Are happening because of the 5 min timeout right?

Besides that everything looks good :)

**Comment by dergoegge** [comment]
That "error" is printed when ever genproofs gets killed because the goroutine that accepts connections fails because the `listener` got closed. 
https://github.com/mit-dci/utreexo/blob/dab732bba431021512e2fac7b18316aeb26a28fe/bridgenode/server.go#L54-L58
The script kills genproofs if ibdsim exits without error:
https://github.com/mit-dci/utreexo/blob/dab732bba431021512e2fac7b18316aeb26a28fe/test/csn_bridge.sh#L147
so in this case it's not because of the 5min timeout.

I am not sure why the ci highlights this message because it's not printed to stderr, but i guess it has the word "error" in it :D

**Comment by kcalvinalvin** [comment]
> That "error" is printed when ever genproofs gets killed because the goroutine that accepts connections fails because the `listener` got closed. 
> 
> https://github.com/mit-dci/utreexo/blob/dab732bba431021512e2fac7b18316aeb26a28fe/bridgenode/server.go#L54-L58
> 
> The script kills genproofs if ibdsim exits without error:
> 
> https://github.com/mit-dci/utreexo/blob/dab732bba431021512e2fac7b18316aeb26a28fe/test/csn_bridge.sh#L147
> 
> so in this case it's not because of the 5min timeout.
> 
> 
> 
> I am not sure why the ci highlights this message because it's not printed to stderr, but i guess it has the word "error" in it :D
> 
> 

ok cool so not even an actual error :)

**Pull request merged**
